tenant: scouredimage
app: kip
service: kip-sls

provider:
  name: aws
  credentials: ${secrets:aws-sls-dev}
  runtime: nodejs8.10
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:custom.stage}
    PUSHER_APP_ID: ${env:PUSHER_APP_ID}
    PUSHER_APP_KEY: ${env:PUSHER_APP_KEY}
    PUSHER_APP_SECRET: ${env:PUSHER_APP_SECRET}
    PUSHER_APP_CLUSTER: ${env:PUSHER_APP_CLUSTER}
    PUSHER_AUTH_ENDPOINT: ${env:PUSHER_AUTH_ENDPOINT}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:custom.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

resources:
  Resources:
    QuestionsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

functions:
  create:
    handler: kip.create
    events:
      - http:
          path: /
          method: post
          cors: true
  get:
    handler: kip.get
    events:
      - http:
          path: /{id}
          method: get
          cors: true
  delete:
    handler: kip.delete
    events:
      - http:
          path: /{id}
          method: delete
          cors: true
  scan:
    handler: kip.scan
    events:
      - http:
          path: ${self:custom.scanEndpoint}
          method: get
          cors: true
  auth:
    handler: kip.auth
    events:
      - http:
          path: ${env:PUSHER_AUTH_ENDPOINT}
          method: post
          cors: true

custom:
  region: ${opt:region, self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  siteName: sandesh-kip-sls-${self:custom.stage}
  scanEndpoint: '/'
  client:
    bucketName: ${self:custom.siteName}
    distributionFolder: static
    indexDocument: index.html

plugins:
  - '@serverless/enterprise-plugin'
  - bootstrap
  - webpack
  - serverless-dotenv-plugin
  - serverless-finch