service: kip-sls

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:custom.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:custom.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

resources:
  Resources:
    QuestionsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

functions:
  create:
    handler: kip.create
    events:
      - http:
          path: /
          method: post
          cors: true
  get:
    handler: kip.get
    events:
      - http:
          path: /{id}
          method: get
          cors: true
  delete:
    handler: kip.delete
    events:
      - http:
          path: /{id}
          method: delete
          cors: true
  scan:
    handler: kip.scan
    events:
      - http:
          path: /
          method: get
          cors: true

custom:
  region: ${opt:region, self:provider.region}
  stage: ${opt:stage, self:provider.stage}

plugins:
  - bootstrap
